config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page, google
import debug_toolbar


urlpatterns = [
    path("", home_page, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("profiles/", include("profiles.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("images/", include("images.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("actions/", include("actions.urls")),
    path("google48bd223165802762.html/", google, name="google"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import (
    image_post_get,
    image_detail_view,
    image_like,
    image_list_view,
    image_ranking,
)


app_name = "images"

urlpatterns = [
    path("", image_list_view, name="list_view"),
    path("create/", image_post_get, name="image_create"),
    path("edit/<int:this_obj_id>", image_post_get, name="image_edit"),
    path("<slug:slug>/<int:img_pk>", image_post_get, name="image_details"),
    path("detail/<int:id>/<slug:slug>", image_detail_view, name="detail_view"),
    path("like/", image_like, name="like"),
    path("ranking/", image_ranking, name="ranking"),
]

images/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.


class Image(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="user_images", on_delete=models.CASCADE
    )
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="images_liked", blank=True
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to="images/%Y/%m/%d/")
    description = models.TextField(blank=True)
    created = models.DateField(
        auto_now_add=True, db_index=True
    )  # Since you use auto_now_add, this datetime is automatically set when the object is created.
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "images:detail_view",
            args=[
                self.id,
                self.slug,
            ],
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # You use db_index=True so that Django creates an index in the database for this field.
    # Database indexes improve query performance. Consider setting db_index=True for fields that you frequently query using
    # filter(), exclude(), or order_by(). ForeignKey fields or fields with unique=True imply the creation of an index. You can
    # also use Meta.index_together or Meta.indexes to create

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ("title", "url", "description")

        # widgets = {"url": forms.HiddenInput}

        def clean_url(self):
            url = self.cleaned_data["url"]
            valid_extensions = ["jpg", "jpeg"]
            extension = url.rsplit(".", 1)[1].lower()
            # split from the first . from right split 1 only
            if extension not in valid_extensions:
                raise forms.ValidationError(
                    "The given URL does not " "match valid image extensions."
                )
            return url

        def save(self, force_insert=False, force_update=False, commit=True):
            image = super().save(commit=False)
            image_url = self.cleaned_data["url"]
            name = slugify(image.title)
            extension = image_url.rsplit(".", 1)[1].lower()
            image_name = f"{name}.{extension}"
            # download image from the given URL
            header = {"User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64)"}
            response = request.urlopen(image_url, header)
            image.image.save(image_name, ContentFile(response.read()), save=False)
            if commit:
                image.save()
            return image

images/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import ImageForm
from .models import Image
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
from django.conf import settings
import redis


r = redis.Redis(
    host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB
)


# Create your views here.


@login_required
def image_list_view(request):
    all_images = None
    following_list_users = request.user.following.values_list("id", flat=True)
    if following_list_users:
        all_images = Image.objects.filter(user__in=following_list_users).order_by(
            "-created"
        )
        # all_images = Image.objects.all().order_by("-created")
        paginator = Paginator(all_images, 10)
        page = request.GET.get("page")
        try:
            all_images = paginator.page(page)
        except PageNotAnInteger:
            all_images = paginator.page(1)
        except EmptyPage:
            if request.is_ajax():
                return HttpResponse("")
            all_images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        context = {"section": "images", "all_images": all_images}
        return render(
            request,
            "images/list_ajax.html",
            context,
        )
    context = {"section": "images", "all_images": all_images}
    return render(request, "images/list.html", context)


@login_required
def image_post_get(request, this_obj_id=None):
    if request.method == "POST" and request.POST["action"] == "upload":
        form = ImageForm(
            data=request.POST,
        )
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, "bookmarked image", new_item)
            messages.success(request, "Image added successfully")
            return redirect(new_item.get_absolute_url())
    elif request.method == "POST" and request.POST["action"] == "save":
        try:
            this_obj_id = Image.objects.get(id=this_obj_id)
        except Image.DoesNotExist:
            raise Http404
        updated_item = ImageForm(
            data=request.POST,
            instance=this_obj_id,
        )
        if updated_item.is_valid():
            updated_item = updated_item.save()
            messages.success(request, "Saved Succesfully")
            return redirect(updated_item.get_absolute_url())
    if this_obj_id:
        try:
            this_obj_id = Image.objects.get(id=this_obj_id)
        except Image.DoesNotExist:
            raise Http404

        form = ImageForm(instance=this_obj_id)
        context = {
            "form": form,
            "section": "images",
            "this_obj_id": this_obj_id,
        }
        return render(request, "images/edit.html", context)

    form = ImageForm(data=request.GET)
    context = {
        "form": form,
        "section": "images",
    }
    return render(request, "images/images.html", context)


@login_required
def image_detail_view(request, id, slug):
    try:
        this_image = Image.objects.get(id=id, slug=slug)
    except Image.DoesNotExist:
        return HttpResponse("Page does not exist")
    total_views = r.incr(f"image:{this_image.id}:views", 0)
    user_just_viewed = r.sadd(f"{this_image.id}", f"{request.user.id}")
    if user_just_viewed:
        # increment total image views by 1
        total_views = r.incr(f"image:{this_image.id}:views", 1)
        # increment image ranking by 1
        # name of set, increamentby, objects of set
        r.zincrby("image_ranking", 1, this_image.id)
    context = {
        "this_image": this_image,
        "section": "images",
        "total_views": total_views,
    }
    return render(request, "images/image_detail_view.html", context)


@login_required
def image_ranking(request):
    # get image ranking dictionary
    # the the_set, 0 starts from lowest, -1 to the last, desc=True descending order
    image_ranking = r.zrange("image_ranking", 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    context = {"section": "images", "most_viewed": most_viewed}
    return render(request, "images/ranking.html", context)


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get("id")
    action = request.POST.get("action")
    if image_id and action:
        try:
            this_image = Image.objects.get(id=image_id)
            if action == "like":
                this_image.users_like.add(request.user)
                create_action(request.user, "likes", this_image)
            else:
                this_image.users_like.remove(request.user)
                create_action(request.user, "Unlikes", this_image)
            return JsonResponse({"status": "ok"})
        except:
            pass
    return JsonResponse({"status": "error"})

images/templates/images/edit.html
{% extends 'base.html' %}


{% block title %}Images{% endblock title %}

{% block content %}

<div class="form-wrapper">
  <form class="for-form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-p">
      <img src="{{ this_obj_id.url }}" class="image-preview">
      {{form}}
      <button class="hover-btn" type="submit" name="action" value="save">Save</button>
    </div>
  </form>
</div>

{% endblock content %}

images/templates/images/image_detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{this_image.title}}{% endblock title %}

{% block content %}

<div class="detail-wrapper">
  {% if messages %}
    {% for msg in messages %}
    <div class="success-messages">{{msg}}</div>
    {% endfor %}
  {% endif %}

  <h1 class="detail-h1">{{this_image.title}}</h1>
  {% load thumbnail %}
    <a href="{{ this_image.url }}">
      <img src="{% thumbnail this_image.image 300x0 %}" class="image-detail">
      <img src="{{ this_image.url }}" class="image-detail">
    </a>

  {% with total_likes=this_image.users_like.count users_like=this_image.users_like.all %}
  <div class="image-info">
    <div class="likes-wrap">
      <span class="count">
        <a href="#" data-id="{{ this_image.id }}"
        data-action="{% if request.user in users_like %}un{% endif %}like"
        class="like like-button">
        {% if request.user not in users_like %}
          <button class="detail-like-btn success like-btn">
          <i class="far fa-thumbs-up fa-2x"></i>
          <p>{{ total_likes }} like{% if total_likes > 1 %}{{ total_likes|pluralize }}{% endif %}</p>
        </button>
        {% else %}
        <button class="detail-like-btn success dislike-btn">
          <i class="far fa-thumbs-down fa-2x"></i>
          {{ total_likes }} like{% if total_likes > 1 %}{{ total_likes|pluralize }}{% endif %}<br>
          Unlike
        </button>
        {% endif %}
        </a>
      </span>
      <span class="views-count">
        {{ total_views }} view{{ total_views|pluralize }}
      </span>
    </div>
    {{ this_image.description|linebreaks }}
  </div>

  <div class="image-likes">
    {% for user in users_like %}
    <div>
      {% if user.user_profile.photo %}
        <img src="{{ user.user_profile.photo.url }}">
        <p>{{ user.user_profile.first_name }}</p>
      {% else %}
        <img src="{% static "img/profile_pic.jpg" %}">
        <p>{{ user.user_profile.first_name }}</p>
      {% endif %}
    </div>
    {% empty %}
      <p>Nobody likes this image yet.</p>
    {% endfor %}
    </div>

{% endwith %}
</div>

{% endblock content %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post("{% url "images:like" %}",
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok') {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');

          // toggle link text
          //$('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
          $('a.like').load(location.href + " .like");
        };
      }
    );
  });
{% endblock domready %}

images/templates/images/images.html
{% extends 'base.html' %}


{% block title %}Images{% endblock title %}

{% block content %}

<div class="form-wrapper">
  <form class="for-form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-p">
      <img src="{{ request.GET.url }}" class="image-preview">
      {{form}}
      <button class="hover-btn" type="submit", value="Login">Upload</button>
    </div>
  </form>
</div>

{% endblock content %}

images/templates/images/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}

<h1>Images bookmarked</h1>

<div id="image-list-div">

{% include "images/list_ajax.html" %}

</div>

{% endblock content %}


{% block domready %}

var page = 1;
var empty_page = false;
var block_request = false;

$(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
            if(data == '') {
                empty_page = true;
            }
            else {
                block_request = false;
                $('#image-list-div').append(data);
                }
        });
    }

});

{% endblock domready %}

images/templates/images/list_ajax.html
{% load thumbnail %}

{% for image in all_images %}

<div class="image">

<a href="{{ image.get_absolute_url }}">

{% thumbnail image.image 300x300 crop="smart" as im %}

<a href="{{ image.get_absolute_url }}">
<img src="{{ image.url }}">
</a>

</a>

<div class="info">

<a href="{{ image.get_absolute_url }}" class="title">

{{ image.title }}

</a>

</div>

</div>

{% endfor %}

images/templates/images/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock %}

{% block content %}

<div  class="rating">
<h1>Images ranking</h1>
  <ol>
  {% for image in most_viewed %}
      <li>
        <a href="{{ image.get_absolute_url }}">
        {{ image.title }}
        </a>
      </li>
  {% endfor %}
  </ol>
</div>
{% endblock %}