config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page, google
import debug_toolbar


urlpatterns = [
    path("", home_page, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("profiles/", include("profiles.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("images/", include("images.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("actions/", include("actions.urls")),
    path("google48bd223165802762.html/", google, name="google"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import (
    image_post_get,
    image_detail_view,
    image_like,
    image_list_view,
    image_ranking,
)


app_name = "images"

urlpatterns = [
    path("", image_list_view, name="list_view"),
    path("create/", image_post_get, name="image_create"),
    path("edit/<int:this_obj_id>", image_post_get, name="image_edit"),
    path("<slug:slug>/<int:img_pk>", image_post_get, name="image_details"),
    path("detail/<int:id>/<slug:slug>", image_detail_view, name="detail_view"),
    path("like/", image_like, name="like"),
    path("ranking/", image_ranking, name="ranking"),
]

profiles/urls.py
from django.urls import path
from .views import dashboard, edit_profile, user_list, user_detail, user_follow

app_name = "profiles"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("edit/", edit_profile, name="edit_profiles"),
    path("users/", user_list, name="user_list"),
    path("users/follow/", user_follow, name="user_follow"),
    path("users/<str:nickname>/", user_detail, name="user_detail"),
]

profiles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


# Create your models here.


class Person_profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_profile"
    )
    first_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=40, null=True, blank=True)
    nickname = models.CharField(max_length=30, unique=True, null=False, blank=False)
    photo = models.ImageField(upload_to="media/users/%Y/%m/%d", blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    country = models.CharField(max_length=40, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    address1 = models.CharField(blank=True, null=True, max_length=50)
    address2 = models.CharField(blank=True, null=True, max_length=50)
    phone = models.CharField(blank=True, null=True, max_length=25)
    zipcode = models.CharField(blank=True, null=True, max_length=10)

    class Meta:
        verbose_name = "Users profile"

    def __str__(self):
        if self.nickname:
            return self.nickname
        else:
            return self.user.email

    def get_full_name(self):
        is_un_named = self.first_name is None and self.last_name is None
        if is_un_named:
            return "Please set your first and last name in your profile"
        else:
            return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("add_later", kwargs={"pk": self.pk})

profiles/forms.py
from django import forms
from django.forms.widgets import DateInput, Input
from .models import Person_profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Person_profile
        fields = (
            "nickname",
            "first_name",
            "last_name",
            "date_of_birth",
            "country",
            "state",
            "city",
            "address1",
            "address2",
            "phone",
            "zipcode",
            "photo",
        )

        widgets = {
            "phone": Input(attrs={"type": "tel", "placeholder": "204873623"}),
            "date_of_birth": DateInput(attrs={"type": "date"}),
        }

    def clean_nickname(self):
        make_nick_lower = self.cleaned_data["nickname"].lower()
        return make_nick_lower

profiles/views.py
from actions.utils import create_action
from django.http.response import HttpResponse
from accounts.models import User
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from .forms import ProfileForm
from django.http import JsonResponse
from accounts.models import Contact
from common.decorators import ajax_required


# Create your views here.


@login_required
def dashboard(request):
    if request.is_ajax() and "action" in request.POST:
        obj = request.POST.get("obj")
        action = request.POST.get("action")
        if action == "delete":
            request.user.user_images.get(id=obj).delete()
            return JsonResponse({"status": "deleted"})
    current_user_images = request.user.user_images.all().order_by("-created")
    paginator = Paginator(current_user_images, 10)
    page = request.GET.get("page")
    try:
        current_user_images = paginator.page(page)
    except PageNotAnInteger:
        current_user_images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        current_user_images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        context = {"section": "images", "current_user_images": current_user_images}
        return render(
            request,
            "profiles/list_ajax.html",
            context,
        )
    context = {
        "section": "dashboard",
        "current_user_images": current_user_images,
        "paginator": paginator,
    }
    return render(request, "profiles/dashboard.html", context)


@login_required
def edit_profile(request):
    form = ProfileForm(
        request.POST or None, request.FILES or None, instance=request.user.user_profile
    )
    if request.method == "POST":
        if form.is_valid():
            form.save()
            if request.POST.get("save") == "save":
                messages.success(request, "Profile updated " "successfully")
                return redirect("profiles:dashboard")
            messages.success(request, "Cancelled " "successfully")
            return redirect("profiles:dashboard")
        else:
            messages.error(request, f"Error updating your profile")
    context = {
        "form": form,
    }
    return render(request, "profiles/edit_profiles.html", context)


@login_required
def user_list(request):
    users = User.objects.select_related("user_profile").filter(is_active=True)
    context = {"section": "people", "users": users}
    return render(request, "profiles/user_list.html", context)


@login_required
def user_detail(request, nickname):
    try:
        this_user = (
            User.objects.select_related("user_profile")
            .prefetch_related("user_images")
            .get(user_profile__nickname=nickname, is_active=True)
        )
    except User.DoesNotExist:
        return HttpResponse("Page does not exist")
    follow_you = this_user.follow_you.filter(user_from=request.user).exists()
    context = {
        "section": "people",
        "this_user": this_user,
        "follow_you": follow_you,
    }
    return render(request, "profiles/user_detail.html", context)


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get("id")
    action = request.POST.get("action")
    if user_id and action:
        try:
            this_user = User.objects.get(id=user_id)
            if action == "follow":
                Contact.objects.get_or_create(user_from=request.user, user_to=this_user)
                create_action(request.user, "is following", this_user)
            else:
                Contact.objects.filter(
                    user_from=request.user, user_to=this_user
                ).delete()
                create_action(request.user, "Unfollows", this_user)
            return JsonResponse({"status": "ok"})
        except User.DoesNotExist:
            return JsonResponse({"status": "error"})
    return JsonResponse({"status": "error"})

profiles/templates/profiles/dashboard.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
    {% if user.user_profile.first_name %}
        Welcome to your dashboard {{user.user_profile.first_name}}
    {% else %}
        Welcome to your dashboard {{user.user_profile.nickname}}
    {% endif %}
{% endblock title %}


{% block content %}
    {% for msg in messages %}
    <div class="error-div"><span>{{msg}}</span></div>
    {% endfor %}

    {% if user.user_profile.first_name %}
        <h1>Welcome to your dashboard {{user.user_profile.first_name}}</h1>
    {% else %}
        <h1>Welcome to your dashboard {{user.user_profile.nickname}}</h1>
    {% endif %}

    {% with total_images_created=paginator.count %}
        <p>Welcome to your dashboard. You have bookmarked 
        {{ total_images_created }} image{{ total_images_created|pluralize }}.</p>
    {% endwith %}

    <p>Drag the following button to your bookmarks toolbar to bookmark images from other websites → 
      <a href="javascript:{% include "images/bookmarklet_launcher.js" %}" class="button">Bookmark it</a>
    </p>
    <p>Or click here to upload a link manually → 
      <a href="{% url "images:image_create" %}">
        <button class="hover-btn">Bookmark</button>
      </a>
    </p>

    <div id="image-list-div">
      {% include "profiles/list_ajax.html" %}
    </div>

{% endblock content %}


{% block domready %}

function btnAndScrool() {
    $(".dashboard-btn").click(function(e) {
    e.preventDefault();
    let obj = $(this).closest(".image").find("a").prop("href");
    obj = obj.split("/");
    let selected = $(this).text().toLowerCase();
    if(selected === "edit") {
      {% comment %} $.post("{% url "images:image_edit" 0 %}".replace(0, obj[5]),
      {
        obj: obj[5],
        action: selected
      },
      function(data) {
          if(data["status"]==="saved") {
              console.log(data);
          }
      })
      console.log("you can edit", obj[5]) {% endcomment %}
    }else if(selected === "delete") {
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.isConfirmed) {
          $.post("{% url "profiles:dashboard" %}",
          {
            obj: obj[5],
            action: selected
          },
          function(data) {
            if(data["status"]==="deleted") {
            }
          });
          Swal.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          ).then((result) => {
            location.reload();
          })
          setTimeout(()=> location.reload(), 5000);//reload after 5 seconds of waiting
          
        }else if (result.dismiss === Swal.DismissReason.cancel) {
          Swal.fire(
            'Cancelled',
            'Your precious file is safe :)',
            'error'
            );
            setTimeout(()=> location.reload(), 5000);//reload after 5 seconds of waiting
        }else if (result.dismiss === Swal.DismissReason.backdrop) {
            console.log("backdrop");
          }
      })// end of swal then
      setTimeout(()=> location.reload(), 60000);//reload after 1 minute of waiting
    };//end of if else
  });//close click function here

}//function declaration end

var page = 1;
var empty_page = false;
var block_request = false;

$(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
        block_request = true;
        page += 1;
        $.get('?page=' + page, function(data) {
            if(data == '') {
                empty_page = true;
            }
            else {
                block_request = false;
                $('#image-list-div').append(data);
                btnAndScrool();
            }
        });
    }
});//window select code end here
btnAndScrool();
{% endblock domready %}

profiles/templates/profiles/edit_profiles.html
{% extends 'base.html' %}

{% block title %}{{ user.user_profile.nickname }} edit ur profile{% endblock title %}


{% block content %}

<div class="form-wrapper">
  <form class="for-form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-p">
    {% for msg in messages %}
      <div class="error-div"><span>{{msg}}</span></div>
    {% endfor %}
      {{form}}
      <div>
        <button class="hover-btn" type="save" name="save" value="save">Save</button>
        <a href="{% url "profiles:dashboard" %}"><button class="hover-btn">Cancel</button></a>
      </div>
    </div>
  </form>
</div>

{% endblock content %}

profiles/templates/profiles/list_ajax.html
{% load thumbnail %}

{% for image in current_user_images %}
  <div class="image">
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">
        {{ image.title }}
      </a>
    </div>

    <div class="dashboard-image">
      <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
          <img src="{{ image.url }}">
        </a>
      </a>
    </div>
    <div class="edit-delete-div">
      <button class="hover-btn dashboard-btn" type="button" onclick="location.href='{% url "images:image_edit" image.id %}'">Edit</button>
      <button class="hover-btn dashboard-btn" type="button">Delete</button>
    </div>
  </div>
{% endfor %}

profiles/templates/profiles/user_detail.html
{% extends "base.html" %}

<!-- {% load images_tags %} Not using this one for now-->
{% load thumbnail %}
{% load static %}

{% block title %}{{ this_user.user_profile.get_full_name }}{% endblock %}

{% block content %}
  <h1>{{ this_user.user_profile.get_full_name }}</h1>
  <div class="profile-info">
  {% if this_user.user_profile.photo %}
    <img src="{% thumbnail this_user.user_profile.photo 180x180 %}" class="user-detail">
  {% else %}
    <img src="{% static "img/profile_pic.jpg" %}" width="193" height="130">
  {% endif %}
  </div>

{% with total_followers=this_user.follow_you.count %}
  <span class="count">
    <span class="total">{{ total_followers }}</span>
      follower{{ total_followers|pluralize }}
    </span>
    
    <a href="#" data-id="{{ this_user.id }}" data-action="{% if follow_you %}un{% endif %}follow" class="follow button">
      {% if request.user == this_user %}
        <!-- Do nothing -->
      {% elif follow_you %}
        <button class="hover-btn follow-unfollow">Unfollow</button>
      {% else %}
        <button class="hover-btn follow-unfollow">Follow</button>
      {% endif %}
    </a>
    
  <div id="image-list-div" class="image-container">
    {% include "images/list_ajax.html" with all_images=this_user.user_images.all %}
  </div>

{% endwith %}

{% endblock content %}



<!-- ajax call function for follow and unfollow -->
{% block domready %}

$('a.follow').click(function(e){

e.preventDefault();

$.post('{% url "profiles:user_follow" %}',

{

id: $(this).data('id'),

action: $(this).data('action')

},

function(data){

if (data['status'] == 'ok') {

var previous_action = $('a.follow').data('action');

// toggle data-action

$('a.follow').data('action',

previous_action == 'follow' ? 'unfollow' : 'follow');

// toggle link text
$('a.follow .follow-unfollow').text(previous_action == 'follow' ? 'Unfollow' : 'Follow');

//
//$('a.follow').load(location.href + " .follow");
// update total followers

var previous_followers = parseInt(

$('span.count .total').text());

$('span.count .total').text(previous_action == 'follow' ?

previous_followers + 1 : previous_followers - 1);

}

}

);

});

{% endblock %}

profiles/templates/profiles/user_list.html
{% extends "base.html" %}

{% load static %}
{% load thumbnail %}


{% block title %}People{% endblock %}

{% block content %}

<h1>People</h1>

<div id="people-list">
  {% for user in users %}
    <div class="user">
      <div class="info">
        <a href="{{ user.get_absolute_url }}" class="title">
          {{ user.user_profile.get_full_name }}
        </a>
      </div>

      <a href="{{ user.get_absolute_url }}">
        {% if user.user_profile.photo.url is not None %}
           <img src="{% thumbnail user.user_profile.photo 180x180 %}">
        {% else %}
          <img src="{% static "img/profile_pic.jpg" %}" width="180" height="180">
          <img src="{% thumbnail user.user_profile.photo 180x180 %}">
        {% endif %}
      </a>
    </div>

{% endfor %}
</div>

{% endblock content %}