accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import login_page, logout_page, sign_up


app_name = "accounts"

urlpatterns = [
    path("login/", login_page, name="login"),
    path("logout/", logout_page, name="logout"),
    path("signup/", sign_up, name="signup"),
    # Django also provides the authentication URL patterns that you just created. You
    # can comment out the authentication URL patterns that you added to the urls.py
    # file of the account application and include django.contrib.auth.urls instead,
    # as follows:
    # from django.urls import path, include
    # # ...
    # urlpatterns = [
    # # ...
    # path('', include('django.contrib.auth.urls')),
    # ]
    # path(
    #     "password_change/",
    #     auth_views.PasswordChangeView.as_view(),
    #     name="password_change",
    # ),
    # path(
    #     "password_change/done/",
    #     auth_views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path(
    #     "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    # ),
    # path(
    #     "password_reset/done/",
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home_page, google
import debug_toolbar


urlpatterns = [
    path("", home_page, name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("profiles/", include("profiles.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("images/", include("images.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("actions/", include("actions.urls")),
    path("google48bd223165802762.html/", google, name="google"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import (
    image_post_get,
    image_detail_view,
    image_like,
    image_list_view,
    image_ranking,
)


app_name = "images"

urlpatterns = [
    path("", image_list_view, name="list_view"),
    path("create/", image_post_get, name="image_create"),
    path("edit/<int:this_obj_id>", image_post_get, name="image_edit"),
    path("<slug:slug>/<int:img_pk>", image_post_get, name="image_details"),
    path("detail/<int:id>/<slug:slug>", image_detail_view, name="detail_view"),
    path("like/", image_like, name="like"),
    path("ranking/", image_ranking, name="ranking"),
]

profiles/urls.py
from django.urls import path
from .views import dashboard, edit_profile, user_list, user_detail, user_follow

app_name = "profiles"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("edit/", edit_profile, name="edit_profiles"),
    path("users/", user_list, name="user_list"),
    path("users/follow/", user_follow, name="user_follow"),
    path("users/<str:nickname>/", user_detail, name="user_detail"),
]

templates/base.html
{% load static %}
{% load social_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/base.css" %}?{% now "U" %}">

    <title>{% block title %}Base{% endblock title %}</title>
</head>
<body>
<div class="overall-wrapper">
    <header class="menu-btn-wrapper">
      <nav>
          <h2 class="nav-h2"><a href="{% url "home" %}">SWISSCODES</h2></a>
          {% if request.user.is_authenticated %}
          <div class="link-menu">
            <a class="{% if section == "home" %}is-active {% endif %}hi" href="{% url "home" %}">Home</a>
            <a class="{% if section == "dashboard" %}is-active {% endif %}hi" href="{% url "profiles:dashboard" %}">Dashboard</a>
            <a  class="{% if section == "images" %}is-active {% endif %}hi" href="{% url "images:list_view" %}">Images</a>
            <a  class="{% if section == "people" %}is-active {% endif %}hi" href="{% url "profiles:user_list" %}">People</a>
            <div class="logout-div">
             <a href="{% url "profiles:edit_profiles" %}">edit</a>
             <a href="{% url "password_change" %}">password</a>
            </div>
            <div class="logout-div">
              <span class="logout-span">Hi {{request.user.user_profile.nickname}}</span>
              <a href="{% url "logout" %}">Logout</a>
            </div>
          </div>
          <button class="burger-button">
            <span class="bar-span"></span>
            <span class="bar-span"></span>
            <span class="bar-span"></span>
          </button>

          {% else %}
            <div class="link-menu">
              <a href="{% url "accounts:login" %}" class="{% if section == "login" %}is-active {% endif %}hi">Login</a>
              <a href="{% url "accounts:signup" %}" class="{% if section == "signup" %}is-active {% endif %}hi">Sign up</a>
            </div>
            <button class="burger-button">
              <span class="bar-span"></span>
              <span class="bar-span"></span>
              <span class="bar-span"></span>
            </button>
          {% endif %}
      </nav>
    </header>

    <div class="empty">
    </div>


    <div class="base-wrapper">
      {% block content %}
      {% endblock content %}
    </div>

    <div class="footer-div">
      <footer class="social-footer">© {% current_year %} – Social app ⋅ Privacy Policy</footer>
    </div>
  </div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" 
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
crossorigin="anonymous">
</script>
<script src="{% static "js/base.js" %}?{% now "U" %}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Welcome Social{% endblock title %}

{% block content%}
{% if request.user.is_authenticated %}
 <div class="home-msg"><h1>Welcome {{user.user_profile.nickname}}</h1></div>
 <div class="span-msg-div">
    <span class="notice-msg">
      I stopped the redis service for now so this application
      can be fully experienced when you
      refreshed on the images the count show's more count
      normally it should only increase per each user view
      but the redis service is not enabled on this server yet
      Thank you for visiting
    </span>
  </div>
  <a href="{% url "images:ranking" %}"><button class="hover-btn">Most Viewed</button></a>

  <div class="what-is-new"><h2>What's happening</h2></div>
  <div id="action-list">
    {% for action in actions %}
      {% include "actions/detail.html" %}
    {% endfor %}
  </div>

{% else %}
  <div class="home-msg"><h1>Welcome guest</h1></div>
  <a href="{% url "accounts:login" %}"><button class="hover-btn">Login</button></a>
  <p>Dont have an account? <a href="{% url "accounts:signup" %}"><button class="hover-btn">Sign up</button></a></p>
{% endif %}

{% endblock content%}